// creamos la interface del pedido (ESTAMOS EN TYPESCRIPT TIPEMOS TODOS LOS QUE PODAMOS)!!!
// Shift + alt + p ==> paste json an code ====> titulo de la interface y nos la crea! 
// NOTA: para que esto funcione previamente debemos copiar el endpoint de la interface.


//Creado el interface vamos a tipar en usePokemonPaginated

// Generated by https://quicktype.io

export interface PokemonPaginatedResponse {
  count: number;
  next: string;
  previous: null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}

export interface SimplePokemon {
  id: string;
  name: string;
  url: string;
  color?: string;
}
